### PR TITLE
Create fresco as an amuse.ext package

### LINKED ISSUE #19: Move Fresco into amuse.ext
This would make sense with the upcoming modular AMUSE.

### PR DESCRIPTION
**Pull request by rieder**
fixes #19

### CODE REVIEW

**Comment by ipelupessy** [comment]
maybe also include the fresco.py standalone as script (will be copied to bin)??

**Comment by rieder** [comment]
Thanks, that would indeed be nice (I’m trying to figure out how that works :) )

**Comment by ipelupessy** [comment]
I think adding scripts="fresco.py" to the setup call is enough..

**Comment by ipelupessy** [comment]
but it needs a shebang

**Comment by rieder** [comment]
done in 0.5.1

**Pull request merged**
